from partitioning_machines.utils.convert_tree import tree_from_sklearn_decision_tree
from partitioning_machines.utils.draw_tree import *
from partitioning_machines.utils.special import *
from partitioning_machines.utils.func_to_cmd import func_to_cmd